name: Build (Linux)
on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Cache conda dependencies
      uses: actions/cache@v2
      with:
        key: conda-cache
        path: /home/runner/.conda/pkgs

    - name: Conda Info
      run: |
        echo $CONDA
        conda info

    - name: Display package caches 1
      run: |
        ls /usr/share/miniconda/pkgs


    - name: Display package caches 2
      run: |
        ls /home/runner/.conda/pkgs
        
    - name: Install mamba
      run: |
        conda install mamba -n base -c conda-forge    

    - name: Install development dependencies
      run: |
        mamba install flake8
        mamba install pytest

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Build the package
      run: |
        python setup.py sdist bdist_wheel

    - name: List files
      run: |
        tree .

    - name: Display package caches 1
      run: |
        ls /usr/share/miniconda/pkgs


    - name: Display package caches 2
      run: |
        ls /home/runner/.conda/pkgs

    - name: Store build output as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: python-package
        path: dist/*


  Publish:
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: python-package

      - name: List files
        run: |
          tree .